#!/bin/sh
DIR=`dirname $0`
meson $DIR \
	-Dmultilib=false \
	-Dnewlib-tinystdio=true \
	-Dnewlib-supplied-syscalls=false \
	-Dnewlib-wide-orient=false\
	-Dnewlib-nano-malloc=true\
	-Dlite-exit=true\
	-Dnewlib-global-atexit=true\
	-Dincludedir=lib/newlib-nano/include \
	-Dlibdir=lib/newlib-nano/lib \
	-Dtests=true \
	--buildtype debug
